version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.1

workflows:
  version: 2
  master:
    jobs:
      - deploy:
          filters:
            branches:
              only: master

commands:
  build:
    steps:
      - checkout
      - aws-cli/install
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies 📦
          command: yarn install --ignore-engines
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
  test:
    steps:
      - run:
          name: Test 🛠
          command: yarn test-core-plugins
  deploy:
    steps:
      - run:
          name: Deploy 🚢
          command: yarn deploy

jobs:
  deploy:
    docker:
      - image: cimg/node:20.18.1
    steps:
      - build
      - test
      - deploy
